### ISSUE TITLE
Example Path01 doesn't work for opengl

### ISSUE THREAD

**Issue by izackp** [turran/enesim#4]
The example uses the enesim_renderer_path.c klass which does not specify an opengl_initial function. This causes the example to fail the check

```
if (klass->opengl_initialize == NULL)
        return EINA_FALSE;
```
inside of enesim_renderer_opengl.c of the enesim_renderer_opengl_setup function

**Comment by turran** [comment]
Are you sure that you have compiled enesim with GL support? Check on the generated config.h file. I have just tested the example and I get a glx window with the path rendered there.

**Comment by izackp** [comment]
Well, not sure because I imported it into an xcode project and manually set all of the defines as well as what files to build.

None the less, the I believe the example uses enesim_renderer_path.c and shouldn't it specify opengl_initialize in order for it to work with enesim_renderer_opengl.c?
```
static void _enesim_renderer_path_class_init(void *k)
{
	Enesim_Renderer_Class *klass;
        ...
        skip
	...
	klass->sw_hints_get = _path_sw_hints;
	klass->sw_setup = _path_sw_setup;
	klass->sw_cleanup = _path_sw_cleanup;
#if BUILD_OPENGL
       //Missing opengl_intiialize
	klass->opengl_setup = _path_opengl_setup;
	klass->opengl_cleanup = _path_opengl_cleanup;
#endif
}
```

**Comment by izackp** [comment]
Ok after looking more into I see you're overriding functions from a 'parent' renderer.. I'll have to look more into that.

**Comment by turran** [comment]
Yes, I just overload the functions that need the 'state' of the path (the shape properties, the renderer properties and the path commands). The opengl_initialize is useful to inform what shaders need to be compiled but no 'state' is needed.

**Comment by izackp** [comment]
yea sorry I forgot I modified enesim_renderer_opengl.c So its my mistake. Sorry lol.
